seed: 42
dataset_name: hellaswag # must match the folder name under tasks/
dataset_path: Rowan/hellaswag
subset: default
split: validation
few_shot_split: train
few_shot_examples: 0
limit: 200

# multiple choice: "question: str", "choices : list", and "answer_index: int"
dataset_preprocessor: task_utils.preprocess_dataset

# placeholder variables must match the dataset column names, formatted using Jinja2
question_format: "\
  This is a commonsense reasoning question about {{ activity_label.strip().lower() }}. The context describes a scenario and we need to choose the most logical continuation. \n\
  Context: {{ question.strip() }}\n\
  Completions: \n\
  {% for choice in choices %}{{ 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'[loop.index0] }}. {{ choice }}\n{% endfor %}"
prompt_format: "{{formatted_question}}\nAnswer: [Return the answer letter only]"
system_prompt: ""
prompt_formatter: multiple_choice 
performance_metrics:
  - accuracy_scalar_with_abstention
  - ece_scalar
  - auroc_scalar

qa_model:
  backend: vllm 
  name: openai/gpt-oss-20b
  repeat: 1
  stop_sequences: [] 
  temperature: 0
  max_tokens: 1024
  max_model_len: 2048
  reasoning_effort: low


grader_model:
  backend: vllm 
  name: openai/gpt-oss-20b
  repeat: 1
  temperature: 0.0
  max_tokens: 1024
  logprobs: 1
  reasoning_effort: low