defaults:
  - _defaults.yaml
  - _self_

generation_type: generation
output_filters:
  - name: regex_extractor
    args:
      regexes:
        - (?i)\bAnswer[:\s]*[\(\[]?\s*([A-D])\s*[\)\]]?
        - (?i)\b([A-D])\s*is\s*the\s*answer\b
        - (?i)\bcorrect\s*answer\s*is:*\s*[\(\[]?\s*([A-D])
        - (?i)\bbest\s*answer\s*is:*\s*[\(\[]?\s*([A-D])
        - (?i)\s*([A-D])
confidence_metrics: length_normalised_log_likelihood
grader: exact_match