defaults:
  - _defaults.yaml
  - _self_

output_filters: null
confidence_metrics: p_true_by_monte_carlo_generation


p_true_mc_model:
  backend: ${qa_model.backend}
  name: ${qa_model.name}
  repeat: 10
  temperature: 1.0
  max_tokens: 512