rounds: 3
seed: 42
dataset_name: squadv2 # must match the folder name under tasks/
dataset_path: rajpurkar/squad_v2
subset: squad_v2
split: validation
few_shot_split: validation
few_shot_examples: 0
limit: 200
results_path: null 
filtered_output_path: null
graded_outputs_path: null
# multiple choice: "question: str", "choices : list", and "answer_index: int"
dataset_preprocessor: task_utils.preprocess_dataset

# placeholder variables must match the dataset column names, formatted using Jinja2
question_format: "Title: {{ title.strip() }}\n\nBackground: {{ context.strip() }}\n\nQuestion: {{ question.strip() }}"   # question formatting template
prompt_format: |
  {{ formatted_question }}

  Answer: 

system_prompt: ""
prompt_formatter: direct_free_form_qa 
generation_type: generation
output_filters: null
confidence_metrics: null
grader: llm_grader
performance_metrics:
  - accuracy_scalar_with_abstention
  - ece_scalar
  - auroc_scalar

qa_model:
  backend: vllm 
  name: openai/gpt-oss-20b
  repeat: 1
  stop_sequences: []
  temperature: 0.1
  max_tokens: 512
  max_model_len: 2048
  reasoning_effort: low


grader_model:
  backend: vllm 
  name: openai/gpt-oss-20b
  repeat: 1
  temperature: 0
  max_tokens: 512
  max_model_len: 2048
  reasoning_effort: low