defaults:
  - _distributional_defaults.yaml
  - _self_


prompt_format: |
  Answer the following question using a succinct (at most one sentence) and full answer. If you are uncertain about your answer to the question, convey this uncertainty linguistically by precisely hedging this answer.
  {{ formatted_question }}
  Answer: 
output_filters: null
confidence_metrics: distributional_linguistic_confidence

qa_model:
  repeat: 1

evaluator_list:
  - linguistic_confidence_judge_model_0
  - linguistic_confidence_judge_model_1
  - linguistic_confidence_judge_model_2

linguistic_confidence_judge_model_0:
  backend: vllm 
  name: openai/gpt-oss-20b
  repeat: 5
  temperature: 1
  max_tokens: 2048
  logprobs: 1
  reasoning_effort: low


linguistic_confidence_judge_model_1:
  backend: vllm 
  name: meta-llama/Llama-3.1-8B-Instruct
  repeat: 5
  temperature: 1
  max_tokens: 2048
  logprobs: 1
  reasoning_effort: low


linguistic_confidence_judge_model_2:
  backend: vllm 
  name: qwen/Qwen3-8B
  repeat: 5
  temperature: 1
  max_tokens: 2048
  logprobs: 1
  reasoning_effort: null