defaults:
  - _distributional_defaults.yaml
  - _self_

output_filters: null
confidence_metrics: distributional_p_true_cont

p_true_cont_model:
  backend: ${qa_model.backend}
  name: ${qa_model.name}
  repeat: 1
  temperature: 1.0
  max_tokens: 1