defaults:
  - _defaults.yaml
  - _self_

prompt_format: |
  Answer the following question using a succinct (at most one sentence) and full answer. Here is the question:
  {{ formatted_question }}
  Please provide your best guess and a confidence score between 0% to 100% in the following JSON format:
  {
    "answer": "Your answer here",
    "confidence_score": number
  }
output_filters: null
confidence_metrics: verbalised_numerical_confidence_with_llm_extractor

qa_model:
  stop_sequences: []